### ISSUE TITLE
draftToHtml is not function

### ISSUE THREAD

**Issue by percysoft** [jpuri/draftjs-to-html#48]
at the time of implementing the function I get the following error:

draftjs_to_html_1.default is not a function
TypeError: draftjs_to_html_1.default is not a function
    at WysiwygCustom._this.getContentText (http://localhost:9001/0.b77eb44ab9d2dac8797c.hot-update.js:86:60)
    at WysiwygCustom._this.onEditorStateChange (http://localhost:9001/0.b77eb44ab9d2dac8797c.hot-update.js:34:42)
    at WysiwygCustom.webpackHotUpdate.1359.WysiwygCustom.componentDidMount (http://localhost:9001/0.b77eb44ab9d2dac8797c.hot-update.js:121:14)
    at commitLifeCycles (http://localhost:9001/static/preview.bundle.js:45867:22)
    at commitAllLifeCycles (http://localhost:9001/static/preview.bundle.js:46961:7)
    at HTMLUnknownElement.callCallback (http://localhost:9001/static/preview.bundle.js:31719:14)
    at Object.invokeGuardedCallbackDev (http://localhost:9001/static/preview.bundle.js:31757:16)
    at invokeGuardedCallback (http://localhost:9001/static/preview.bundle.js:31806:29)
    at commitRoot (http://localhost:9001/static/preview.bundle.js:47100:7)
    at completeRoot (http://localhost:9001/static/preview.bundle.js:48115:34)

**Comment by geoff5802** [comment]
I had recently versioned up from 0.8.3 to 0.8.4 and bumped into the same error. I've gone back to 0.8.3 while I try and understand this error more.

**Comment by feather-aurelie** [comment]
I'm getting this error even with 0.8.3 - any update on that issue?

**Comment by plat123456789** [comment]
I use the following code to solve this error

const draftToHtml = require("draftjs-to-html").default;

or

import draftToHtml from 'draftjs-to-html';

**Comment by muj-beg** [comment]
This is a *breaking change* for any existing code depending on this lib.  Considering it was a minor version bump -- this is very unexpected :disappointed: .

**Comment by mpochowski** [comment]
I fixed it with:
```
import * as draftToHtml from 'draftjs-to-html';
```
